name: Keep Bot Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # ğŸ” Cada 5 minutos
  workflow_dispatch:       # Permite ejecutarlo manualmente tambiÃ©n

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Mantener bot activo
        run: |
          echo "Haciendo ping a tu bot en Render..."
          curl -I https://mr-mewsley.onrender.com
